# Generated by Django 4.2.14 on 2024-08-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellidos', models.CharField(max_length=15)),
                ('numero_celular', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
    ]
