# Generated by Django 4.2.14 on 2024-07-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_numeros_prueba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('reservado_en', models.DateTimeField(auto_now_add=True)),
                ('expiracion', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='title',
        ),
        migrations.AddField(
            model_name='prueba',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prueba',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
