# Generated by Django 4.2.14 on 2024-07-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_reserva_remove_prueba_subtitle_remove_prueba_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
