# Generated by Django 4.2.14 on 2024-08-04 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_prueba_alter_reserva_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='reservado_en',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 3, 42, 35, 706876, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
