# Generated by Django 4.2.14 on 2024-08-04 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_reserva_reservado_en_alter_reserva_expiracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 4, 41, 42, 894309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
