# Generated by Django 4.2.14 on 2024-08-04 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_reserva_expiracion_alter_reserva_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 4, 56, 58, 601334, tzinfo=datetime.timezone.utc)),
        ),
    ]
