# Generated by Django 4.2.14 on 2024-08-04 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_reserva_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 5, 7, 55, 311498, tzinfo=datetime.timezone.utc)),
        ),
    ]
