# Generated by Django 4.2.14 on 2024-08-04 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_reserva_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 21, 34, 24, 535497, tzinfo=datetime.timezone.utc)),
        ),
    ]
