# Generated by Django 4.2.14 on 2024-08-05 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_reserva_pagado_alter_reserva_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='apellidos',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_celular',
            field=models.CharField(default=2222222222, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 2, 27, 41, 209820, tzinfo=datetime.timezone.utc)),
        ),
    ]
