# Generated by Django 4.2.14 on 2024-08-05 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_reserva_apellidos_reserva_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='expiracion',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 2, 28, 37, 328867, tzinfo=datetime.timezone.utc)),
        ),
    ]
