# Generated by Django 4.2.14 on 2024-08-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_reserva_expiracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='expiracion',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_celular',
            field=models.CharField(max_length=10),
        ),
    ]
