# Generated by Django 4.2.14 on 2024-08-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_reserva_expiracion_alter_reserva_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='apellidos',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
    ]
