# Generated by Django 4.2.14 on 2024-07-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='anulate',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(editable=False, max_length=15, unique=True, verbose_name='Nombres '),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='shor_name',
            field=models.CharField(max_length=5, unique=True, verbose_name='Numero'),
        ),
    ]
